/**
 * Shared helpers for the setup and doctor scripts.
 *
 * pi reads provider credentials from the environment, so pi-coffee can be configured
 * without ever running `pi`'s own `/login` flow: we write a small env file under
 * the data directory and the daemon loads it before spawning workers.
 */
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

/** Providers pi understands, mapped to their primary API-key environment variable. */
export const PROVIDER_KEY_VARS = {
  anthropic: "ANTHROPIC_API_KEY",
  antling: "ANT_LING_API_KEY",
  openai: "OPENAI_API_KEY",
  deepseek: "DEEPSEEK_API_KEY",
  nvidia: "NVIDIA_API_KEY",
  gemini: "GEMINI_API_KEY",
  mistral: "MISTRAL_API_KEY",
  groq: "GROQ_API_KEY",
  cerebras: "CEREBRAS_API_KEY",
  xai: "XAI_API_KEY",
  openrouter: "OPENROUTER_API_KEY",
  fireworks: "FIREWORKS_API_KEY",
  together: "TOGETHER_API_KEY",
  baseten: "BASETEN_API_KEY",
  moonshot: "MOONSHOT_API_KEY",
  minimax: "MINIMAX_API_KEY",
  zai: "ZAI_API_KEY",
  meta: "META_API_KEY",
  huggingface: "HF_TOKEN",
};

/** True for values that need quoting when written into a shell-sourced file. */
function shellQuote(value) {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function unquote(value) {
  if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) {
    return value.slice(1, -1).replace(/'\\''/g, "'");
  }
  if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
    return value.slice(1, -1);
  }
  return value;
}

/** Environment variable that carries the API key for a provider. */
export function apiKeyVarFor(provider) {
  const normalized = String(provider || "").trim().toLowerCase();
  if (PROVIDER_KEY_VARS[normalized]) return PROVIDER_KEY_VARS[normalized];
  return `${normalized.replace(/[^a-z0-9]+/g, "_").toUpperCase()}_API_KEY`;
}

/** Where the generated env file lives. */
export function envFilePath(env = process.env) {
  return env.PI_COFFEE_ENV_FILE || join(homedir(), ".pi-coffee", "env");
}

/** Parse a KEY=VALUE file (shell-sourced format). */
export function parseEnvFile(text) {
  const out = {};
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    out[line.slice(0, eq).trim()] = unquote(line.slice(eq + 1).trim());
  }
  return out;
}

/** Load the env file into process.env without overwriting anything already set. */
export function loadEnvFile(file = envFilePath(), { override = false } = {}) {
  if (!existsSync(file)) return { file, loaded: false, values: {} };
  const values = parseEnvFile(readFileSync(file, "utf8"));
  for (const [key, value] of Object.entries(values)) {
    if (override || process.env[key] === undefined) process.env[key] = value;
  }
  return { file, loaded: true, values };
}

/** Write the env file with restrictive permissions. */
export function writeEnvFile(entries, file = envFilePath()) {
  mkdirSync(dirname(file), { recursive: true });
  const lines = [
    "# Generated by `pi-coffee` setup. Contains secrets - keep this file private.",
    "# Re-run `npm run setup` to change it, then restart the daemon.",
    "",
  ];
  for (const [key, value] of Object.entries(entries)) lines.push(`${key}=${shellQuote(String(value))}`);
  writeFileSync(file, lines.join("\n") + "\n", { mode: 0o600 });
  chmodSync(file, 0o600);
  return file;
}
